### ISSUE TITLE
Output for Scala

### ISSUE THREAD

**Issue by yossigil** [OriRoth/fling#15]

**Comment by OriRoth** [comment]
@yossigil Scala has Java's type erasure but no raw types, so the Java solution for instantiating
the fluent interfaces does not hold. I implemented a brute-force solution, where fluent API classes
accept type variable instantiations in the constructor:
```scala
class MyClass[T](val t: T) { /*...use t when T value is needed...*/ }
```
The solution proposed [here](https://stackoverflow.com/a/1306136/8130015), to instantiate type variables, did not work properly.
